TrajectoryPlannerROS:

  holonomic_robot: false
  acc_lim_x: 1.2
  acc_lim_y: 1.2
  acc_lim_theta: 1.2

  min_vel_x: -0.1
  max_vel_x: 0.6
  max_vel_theta: 0.1
  sim_time: 1.6
  meter_scoring: true
  pdist_scale: 1.5
