TrajectoryPlannerROS:

  holonomic_robot: false
  acc_lim_x: 2
  acc_lim_y: 2
  acc_lim_theta: 2

  min_vel_x: 0.2
  max_vel_x: 1.0
  max_vel_theta: 0.8
  sim_time: 1.6
  meter_scoring: true
  pdist_scale: 1.5

  controller_frequency: 3
