map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.1

robot_radius: 0.0 
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

#footprint: [ [0.1, 0.1], [-0.1, 0.1], [-0.1, -0.1], [0.1, -0.1] ]
