map_type: costmap

obstacle_range: 4
raytrace_range: 6

transform_tolerance: 0.3

robot_radius: 0.25 
inflation_radius: 0.05

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}


