global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 1.0
   publish_frequency: 0.5
   width: 15.0
   height: 15.0
   resolution: 0.1
   static_map: true
   rolling_window: false
